/* eslint-disable @typescript-eslint/no-var-requires */
const colors = require('tailwindcss/colors')
const defaultTheme = require('tailwindcss/defaultTheme')

console.log('\n')
console.log(`   ✅ TailwindCSS Config \n`)
console.log(`   ----------- \n`)

delete colors.lightBlue
delete colors.warmGray
delete colors.trueGray
delete colors.coolGray
delete colors.blueGray
delete defaultTheme.colors

module.exports = {
  mode: 'jit',
  content: ['./src/**/*.html', './src/**/*.{ts,tsx}', './pages/**/*.{ts,tsx}'],
  presets: [],
  darkMode: 'class', // or 'media' or 'class'
  corePlugins: {
    boxSizing: false,
  },
  theme: {
    ...defaultTheme,
    extend: {
      colors: {
        ...colors,
        primary: {
          disabled: '#333333',
          default: '#0070F3',
          hover: '#005fcf',
          pressed: '#005fcf',
          'default-flat': '#001835',
        },
        secondary: {
          disabled: '#333333',
          default: '#7928ca',
          hover: '#6622ab',
          pressed: '#6622ab',
          'default-flat': '#1c0631',
        },
        warning: {
          disabled: '#333333',
          default: '#f5a623',
          hover: '#cf8d1e',
          pressed: '#cf8d1e',
          'default-flat': '#3d2705',
        },
        danger: {
          disabled: '#333333',
          default: '#f21361',
          hover: '#cd1052',
          pressed: '#cd1052',
          'default-flat': '#3c0216',
        },
        info: {
          disabled: '#333333',
          default: '#55B7B4',
          hover: '#489b98',
          pressed: '#489b98',
          'default-flat': '#206C7A',
        },
        success: {
          disabled: '#333333',
          default: '#17c964',
          hover: '#13aa55',
          pressed: '#13aa55',
          'default-flat': '#033116',
        },
        nextui: {
          blue: {
            '100': '#bfd8fc',
            '200': '#98D5FD',
            '300': '#64B8FB',
            '400': '#3D9CF7',
            '500': '#0070F3',
            '600': '#0056D0',
            '700': '#0040AE',
            '800': '#002D8C',
            '900': '#001835',
          },
          purple: {
            '100': '#dbc8f0',
            '200': '#DDA9F9',
            '300': '#C17CEF',
            '400': '#A258DF',
            '500': '#7928ca',
            '600': '#5E1DAD',
            '700': '#461491',
            '800': '#310C75',
            '900': '#1c0631',
          },
          green: {
            '100': '#c5f0d5',
            '200': '#A1F9AC',
            '300': '#6FEE8D',
            '400': '#4ADE7B',
            '500': '#17c964',
            '600': '#10AC63',
            '700': '#0B905F',
            '800': '#077457',
            '900': '#033116',
          },
          yellow: {
            '100': '#fce6c7',
            '200': '#FEE7A6',
            '300': '#FCD57A',
            '400': '#F9C258',
            '500': '#f5a623',
            '600': '#D28519',
            '700': '#B06811',
            '800': '#8E4D0B',
            '900': '#3d2705',
          },
          red: {
            '100': '#fbc4d5',
            '200': '#FDA0A5',
            '300': '#FB7085',
            '400': '#F74C77',
            '500': '#f21361',
            '600': '#D00D65',
            '700': '#AE0963',
            '800': '#8C065C',
            '900': '#3c0216',
          },
          cyan: {
            '100': '#EEFFF4',
            '200': '#DDFFED',
            '300': '#CCFFE9',
            '400': '#BFFFEA',
            '500': '#AAFFEC',
            '600': '#7CDBCF',
            '700': '#55B7B4',
            '800': '#368D93',
            '900': '#206C7A',
          },
          pink: {
            '100': '#FFDBE7',
            '200': '#FFB8D6',
            '300': '#FF94CC',
            '400': '#FF7ACC',
            '500': '#ff4ecd',
            '600': '#DB39BD',
            '700': '#B727AA',
            '800': '#921893',
            '900': '#6E0E7A',
          },
          gray: {
            '100': '#F4F4F4',
            '200': '#EAEAEA',
            '300': '#C1C1C1',
            '400': '#999999',
            '500': '#888888',
            '600': '#666666',
            '700': '#444444',
            '800': '#333333',
            '900': '#111111',
          },
        },
      },
      boxShadow: {
        nextui: '0 4px 14px 0 var(--tw-shadow-color)',
      },
      scale: {
        97: '0.97',
        98: '0.98',
        99: '0.99',
      },
      transitionProperty: {
        ...defaultTheme.transitionProperty,
        width: 'width',
        height: 'height',
      },
    },
  },
  variants: {
    accessibility: ['responsive', 'focus-within', 'focus'],
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    animation: ['responsive'],
    appearance: ['responsive'],
    backdropBlur: ['responsive'],
    backdropBrightness: ['responsive'],
    backdropContrast: ['responsive'],
    backdropFilter: ['responsive'],
    backdropGrayscale: ['responsive'],
    backdropHueRotate: ['responsive'],
    backdropInvert: ['responsive'],
    backdropOpacity: ['responsive'],
    backdropSaturate: ['responsive'],
    backdropSepia: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundBlendMode: ['responsive'],
    backgroundClip: ['responsive'],
    backgroundColor: [
      'responsive',
      'dark',
      'group-hover',
      'focus-within',
      'hover',
      'focus',
    ],
    backgroundImage: ['responsive'],
    backgroundOpacity: [
      'responsive',
      'dark',
      'group-hover',
      'focus-within',
      'hover',
      'focus',
    ],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    backgroundSize: ['responsive'],
    backgroundOrigin: ['responsive'],
    blur: ['responsive'],
    borderCollapse: ['responsive'],
    borderColor: [
      'responsive',
      'dark',
      'group-hover',
      'focus-within',
      'hover',
      'focus',
    ],
    borderOpacity: [
      'responsive',
      'dark',
      'group-hover',
      'focus-within',
      'hover',
      'focus',
    ],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['responsive'],
    boxDecorationBreak: ['responsive'],
    boxShadow: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
    boxSizing: ['responsive'],
    brightness: ['responsive'],
    clear: ['responsive'],
    container: ['responsive'],
    contrast: ['responsive'],
    cursor: ['responsive'],
    display: ['responsive'],
    divideColor: ['responsive', 'dark'],
    divideOpacity: ['responsive', 'dark'],
    divideStyle: ['responsive'],
    divideWidth: ['responsive'],
    dropShadow: ['responsive'],
    fill: ['responsive'],
    filter: ['responsive'],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    float: ['responsive'],
    fontFamily: ['responsive'],
    fontSize: ['responsive'],
    fontSmoothing: ['responsive'],
    fontStyle: ['responsive'],
    fontVariantNumeric: ['responsive'],
    fontWeight: ['responsive'],
    gap: ['responsive'],
    gradientColorStops: ['responsive', 'dark', 'hover', 'focus'],
    grayscale: ['responsive'],
    gridAutoColumns: ['responsive'],
    gridAutoFlow: ['responsive'],
    gridAutoRows: ['responsive'],
    gridColumn: ['responsive'],
    gridColumnEnd: ['responsive'],
    gridColumnStart: ['responsive'],
    gridRow: ['responsive'],
    gridRowEnd: ['responsive'],
    gridRowStart: ['responsive'],
    gridTemplateColumns: ['responsive'],
    gridTemplateRows: ['responsive'],
    height: ['responsive'],
    hueRotate: ['responsive'],
    inset: ['responsive'],
    invert: ['responsive'],
    isolation: ['responsive'],
    justifyContent: ['responsive'],
    justifyItems: ['responsive'],
    justifySelf: ['responsive'],
    letterSpacing: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: ['responsive'],
    listStyleType: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    mixBlendMode: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive'],
    opacity: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
    order: ['responsive'],
    outline: ['responsive', 'focus-within', 'focus'],
    overflow: ['responsive'],
    overscrollBehavior: ['responsive'],
    padding: ['responsive'],
    placeContent: ['responsive'],
    placeItems: ['responsive'],
    placeSelf: ['responsive'],
    placeholderColor: ['responsive', 'dark', 'focus'],
    placeholderOpacity: ['responsive', 'dark', 'focus'],
    pointerEvents: ['responsive'],
    position: ['responsive'],
    resize: ['responsive'],
    ringColor: ['responsive', 'dark', 'focus-within', 'focus'],
    ringOffsetColor: ['responsive', 'dark', 'focus-within', 'focus'],
    ringOffsetWidth: ['responsive', 'focus-within', 'focus'],
    ringOpacity: ['responsive', 'dark', 'focus-within', 'focus'],
    ringWidth: ['responsive', 'focus-within', 'focus'],
    rotate: ['responsive', 'hover', 'focus'],
    saturate: ['responsive'],
    scale: ['responsive', 'hover', 'focus'],
    sepia: ['responsive'],
    skew: ['responsive', 'hover', 'focus'],
    space: ['responsive'],
    stroke: ['responsive'],
    strokeWidth: ['responsive'],
    tableLayout: ['responsive'],
    textAlign: ['responsive'],
    textColor: [
      'responsive',
      'dark',
      'group-hover',
      'focus-within',
      'hover',
      'focus',
    ],
    textDecoration: [
      'responsive',
      'group-hover',
      'focus-within',
      'hover',
      'focus',
    ],
    textOpacity: [
      'responsive',
      'dark',
      'group-hover',
      'focus-within',
      'hover',
      'focus',
    ],
    textOverflow: ['responsive'],
    textTransform: ['responsive'],
    transform: ['responsive'],
    transformOrigin: ['responsive'],
    transitionDelay: ['responsive'],
    transitionDuration: ['responsive'],
    transitionProperty: ['responsive'],
    transitionTimingFunction: ['responsive'],
    translate: ['responsive', 'hover', 'focus'],
    userSelect: ['responsive'],
    verticalAlign: ['responsive'],
    visibility: ['responsive'],
    whitespace: ['responsive'],
    width: ['responsive'],
    wordBreak: ['responsive'],
    zIndex: ['responsive', 'focus-within', 'focus'],
  },
  plugins: [],
}
