import '../styles/globals.scss'

import type { AppProps } from 'next/app'
import Head from 'next/head'
import Image from 'next/image'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Gu ask real ideas</title>
        <meta name='description' content='Generated by TanawatDEVz' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Component {...pageProps} />

      <footer>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}

export default MyApp
